# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Roirrow Wang
email: roirrowwang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Dance like no one is watching.
    Sing like no one is listening.
    Work like you don't need the money.
    Love like you've never been hurt.
    Live life everyday as if it were your last.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: roirrow

# Build settings
markdown: kramdown
